import { useEffect, useRef, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ModalFooter, CancelButton, PrimaryButton, FormAlert } from './modal-shell';
import { FileText, Loader2, CheckCircle2, Download } from 'lucide-react';
import { useCreateReport, useDownloadReport, useReportStatus, useReportTemplates } from '@/lib/api/queries';
import { dataMode } from '@/lib/api/client';
import { useSelectedProject } from '@/lib/project-context';
import { formatBytes } from '@/lib/utils';

/**
 * Builds a PDF of the current project with the given report template (default: executive
 * summary) and offers it for download when ready.
 */
export function ExportPdfModal({ onClose, template = 'executive-summary' }: { onClose: () => void; template?: string }) {
  const { project, projectId } = useSelectedProject();
  const templates = useReportTemplates().data;
  const chosen = templates?.find((t) => t.key === template);
  const sections = chosen?.defaultSections ?? ['KPIs', 'Site Audit', 'Keywords', 'Backlinks', 'Competitors'];
  const createReport = useCreateReport();
  const download = useDownloadReport();
  const queryClient = useQueryClient();
  const [reportId, setReportId] = useState<string | null>(null);
  const status = useReportStatus(reportId);
  const started = useRef(false);

  // Start generating as soon as the dialog opens (once templates and the project are known).
  useEffect(() => {
    if (started.current || dataMode === 'demo' || !projectId || !templates) return;
    started.current = true;
    createReport.mutate(
      { projectId, template, format: 'pdf', dateRangeDays: 30, sections },
      { onSuccess: (report) => setReportId(report.id) }
    );
  }, [projectId, templates, template, sections, createReport]);

  const report = status.data;
  const ready = report?.status === 'completed';
  const failed = report?.status === 'failed';

  useEffect(() => {
    if (ready || failed) void queryClient.invalidateQueries({ queryKey: ['/reports'] });
  }, [ready, failed, queryClient]);

  const error =
    dataMode === 'demo'
      ? 'Exports are generated by the RankPulse API, which isn’t connected in demo mode.'
      : createReport.error?.message ?? status.error?.message ?? (failed ? report?.errorMessage ?? 'The export failed.' : download.error?.message);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 rounded-xl border bg-muted/30 p-4">
        <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary">
          <FileText className="h-5 w-5" />
        </span>
        <div className="flex-1">
          <p className="text-sm font-semibold">{chosen?.name ?? 'SEO Report'} Export</p>
          <p className="text-xs text-muted-foreground">
            PDF{report?.fileSize ? ` · ${formatBytes(report.fileSize)}` : ''}{project ? ` · ${project.name}` : ''}
          </p>
        </div>
        {ready ? (
          <CheckCircle2 className="h-5 w-5 text-success" />
        ) : !error ? (
          <Loader2 className="h-5 w-5 animate-spin text-primary" />
        ) : null}
      </div>

      {!ready && !error && (
        <div className="h-2 overflow-hidden rounded-full bg-muted">
          <div className="h-full w-2/3 animate-pulse rounded-full bg-gradient-to-r from-primary to-accent" />
        </div>
      )}

      <FormAlert>{error}</FormAlert>

      <div>
        <p className="text-sm font-semibold">Included Sections</p>
        <div className="mt-2 space-y-1.5">
          {sections.map((s) => (
            <div key={s} className="flex items-center gap-2 rounded-lg border bg-muted/30 px-3 py-2 text-sm">
              <CheckCircle2 className="h-4 w-4 text-success" />
              <span className="text-muted-foreground">{s}</span>
            </div>
          ))}
        </div>
        <p className="mt-2 text-xs text-muted-foreground">The file is also saved under Reports.</p>
      </div>

      <ModalFooter>
        <CancelButton onClose={onClose} />
        <PrimaryButton disabled={!ready || download.isPending} onClick={() => reportId && download.mutate(reportId)}>
          <span className="flex items-center gap-1.5">
            {download.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
            {ready ? 'Download PDF' : 'Preparing…'}
          </span>
        </PrimaryButton>
      </ModalFooter>
    </div>
  );
}
